#!/bin/sh

# autostart
picom -b --experimental-backends
~/.config/polybar/scripts/launch.sh
feh --no-fehbg --bg-fill ~/wallpapers/spaceman.jpg
flameshot &
dunst &

export DESKTOP_COUNT=$(bspc query -M | wc -l)
pgrep -x sxhkd > /dev/null || sxhkd &

# rename desktops
i=1
for monitor in $(bspc query -M); do
	bspc desktop $monitor:\^1 -n $i
	((i++))
done

bspc config border_width			0
bspc config window_gap				20
bspc config split_ratio				0.5
bspc config focus_follows_pointer	true
