#!/bin/sh

# autostart
picom --experimental-backends &
$XDG_CONFIG_HOME/polybar/scripts/launch.sh
feh --no-fehbg --bg-fill ~/wallpapers/castle.jpg
pgrep -x sxhkd || sxhkd &
pgrep -x flameshot || flameshot &
pkill -x dunst ; dunst &

# WM config
bspc config border_width			0
bspc config window_gap				20
bspc config split_ratio				0.5
bspc config focus_follows_pointer	true
