#!/usr/bin/bash

# autostart
picom -b --experimental-backends
~/.config/polybar/scripts/launch.sh
feh --no-fehbg --bg-fill ~/wallpapers/ok-city.jpg
flameshot &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width			0
bspc config window_gap				20
bspc config split_ratio				0.5
bspc config focus_follows_pointer	true
