#!/bin/sh

# autostart
pgrep -x picom || picom -b --experimental-backends
~/.config/polybar/scripts/launch.sh
feh --no-fehbg --bg-fill ~/wallpapers/bamboo.png
pgrep -x sxhkd || sxhkd &
pgrep -x dunst || dunst &
pgrep -x flameshot  || flameshot &

# rename desktops
export DESKTOP_COUNT=$(bspc query -M | wc -l)
i=1
for monitor in $(bspc query -M); do
	bspc desktop $monitor:\^1 -n $i
	i=$((i+1))
done

# WM config
bspc config border_width			0
bspc config window_gap				20
bspc config split_ratio				0.5
bspc config focus_follows_pointer	true
