local options = { noremap = true }
vim.api.nvim_set_keymap('n', 'Y', 'y$', options)
vim.api.nvim_set_keymap('n', '0', '^', options)
vim.api.nvim_set_keymap('n', '<C-h>', '<C-W>h', options)
vim.api.nvim_set_keymap('n', '<C-j>', '<C-W>j', options)
vim.api.nvim_set_keymap('n', '<C-k>', '<C-W>k', options)
vim.api.nvim_set_keymap('n', '<C-l>', '<C-W>l', options)
vim.api.nvim_set_keymap('n', '<C-Up>', ':res +2<CR>', options)
vim.api.nvim_set_keymap('n', '<C-Down>', ':res -2<CR>', options)
vim.api.nvim_set_keymap('n', '<C-Left>', ':vertical res -2<CR>', options)
vim.api.nvim_set_keymap('n', '<C-Right>', ':vertical res +2<CR>', options)
vim.api.nvim_set_keymap('n', '<Tab>', 'gt', options)
vim.api.nvim_set_keymap('n', '<S-Tab>', 'gT', options)
vim.api.nvim_set_keymap('n', '<C-q>', ':noh<CR>', options)
vim.api.nvim_set_keymap('i', '{<CR>', '{<CR>}<Esc>O', options)
vim.api.nvim_set_keymap('i', '[<CR>', '[<CR>]<Esc>O', options)
vim.api.nvim_set_keymap('i', '(<CR>', '(<CR>)<Esc>O', options)
vim.api.nvim_set_keymap('i', '<C-f>', '<C-x><C-f>', options)
