# XDG base directory variables
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_CACHE_HOME=$HOME/.cache

# clean up the home directory
export ZDOTDIR=$XDG_CONFIG_HOME/zsh
export HISTFILE=$XDG_CACHE_HOME/zsh/history
export GDBHISTFILE=$XDG_CACHE_HOME/gdb/history
export SQLITE_HISTORY=$XDG_CACHE_HOME/sqlite/history
export XINITRC=$XDG_CONFIG_HOME/X11/xinitrc
export CARGO_HOME=$XDG_DATA_HOME/cargo
export RUSTUP_HOME=$XDG_DATA_HOME/rustup
export GRIPHOME=$XDG_CACHE_HOME/grip
export GNUPGHOME=$XDG_DATA_HOME/gnupg
export XAUTHORITY=$XDG_RUNTIME_DIR/Xauthority
export PASSWORD_STORE_DIR=$XDG_DATA_HOME/pass
export LESSHISTFILE=-

# other stuff
export PATH="$XDG_DATA_HOME/cargo/bin:$PATH"
export HISTSIZE=1000
export SAVEHIST=1000
export EDITOR=nvim
export VISUAL=nvim
export BROWSER=firefox
export PAGER=less
