# The following lines were added by compinstall
zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' expand suffix
zstyle ':completion:*' file-sort name
zstyle ':completion:*' group-name ''
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'r:|[._-]=** r:|=**' '+l:|=* r:|=*'
zstyle ':completion:*' preserve-prefix '//[^/]##/'
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true
zstyle :compinstall filename '/home/yep/.zshrc'
autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=500
SAVEHIST=500
unsetopt beep nomatch
bindkey -v
# End of lines configured by zsh-newuser-install

autoload -Uz vcs_info
precmd() { vcs_info }
setopt COMPLETE_ALIASES
setopt PROMPT_SUBST
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:*' formats "%F{blue}%b%f "
zstyle ':completion:*' menu select
zstyle ':completion::complete:*' gain-privileges 1
bindkey '\e[A' history-search-backward
bindkey '\e[B' history-search-forward
bindkey "^?" backward-delete-char
bindkey '^R' history-incremental-search-backward
zmodload zsh/complist
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history

alias ls='ls --color=auto'
alias grep='grep --color'
alias vim=nvim
alias vi=nvim
alias tmux='tmux -f ~/.config/tmux/tmux.conf'
alias menfou="git add . ; git commit -m 'menfou' ; git push"
alias gcw='gcc -Wall -Werror -Wextra -g3 -O0'
alias valcheck='valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes'
alias norm=norminette
alias make='make -s'
alias nc=ncat
alias ip='ip -color'

export EDITOR=nvim
export VISUAL=nvim
export KEYTIMEOUT=1
export PROMPT='%B%F{yellow}%3~%f ${vcs_info_msg_0_}%(?.%F{green}❯%f.%F{red}❯%f)%b '
export LESS_TERMCAP_mb=$'\e[1;34m'
export LESS_TERMCAP_md=$'\e[1;34m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;31m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;33m'
if type rg &> /dev/null; then
	export FZF_DEFAULT_COMMAND='rg --files'
	export FZF_DEFAULT_OPTS='-m --height 50% --border'
fi
